### PR TITLE
update to the IOS XE part

### PR DESCRIPTION
**Pull request by rschmied**
- Additional small changes to the documentation
- added some refactoring to the command sending logic based on Jan Lindblad's comments which should result in better / more robust handling of send/expect with device.
- tested script -- created box worked fine w/ IOS XE 16.03.02

### CODE REVIEW

**Comment by rschmied** [comment]
Not sure why I get all these additional commits since most (all?) of those are already merged into master. Obviously, since only two files have changed. The mysteries of Git.

**Comment by glennmatthews** [comment]
Changes look reasonable to me. There's some similarity to a few of the changes I made for XR in #22 - a good reminder that in the long-term we want to combine the common logic into a shared script.

**Comment by glennmatthews** [comment]
Can you try "git remote add upstream https://github.com/ios-xr/iosxrv-x64/vbox ; git fetch upstream ; git rebase upstream/master" for your branch and see if that cleans up the commit history?

**Comment by glennmatthews** [comment]
Merged manually. Thanks for the contribution!

**Pull request closed without merging**
